GET  http://localhost:3001/categories
Content-Type: application/json

###
POST  http://localhost:3001/categories
Content-Type: application/json



###
GET  http://localhost:3001/products
Content-Type: application/json



